cc_library(
    name = "vector",
    hdrs = ["vector.h",
			"Collection.h"],
	deps = ["//src/iterator:iterator"],
    visibility = ["//visibility:public"],
    )

cc_library(
	name = "collection",
	hdrs = ["Collection.h"],
    visibility = ["//visibility:public"],
	)
